export const USER_MESSAGES = {
  REGISTER_SUCCESS: 'Register success',
  LOGIN_SUCCESS: 'Login success',
  VALIDATION_ERROR: 'Validation error',
  EMAIL_EXISTS: 'Email already exists',
  NAME_REQUIRED: 'Name is required',
  NAME_LENGTH: 'Name must be between 1 and 50 characters',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Email is invalid',
  EMAIL_IS_EXISTED: 'Email already exists',
  EMAIL_OR_PASSWORD_INVALID: 'Email or password is invalid',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_LENGTH: 'Password must be between 6 and 20 characters',
  PASSWORD_MUST_BE_STRONG:
    'Password must be strong with at least one uppercase letter, one lowercase letter, one number, and one symbol',
  CONFIRM_PASSWORD_MISMATCH: 'Confirm password does not match password',
  CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be strong with at least one uppercase letter, one lowercase letter, one number, and one symbol',
  LOGIN_FAILED: 'Login Failed',
  DATE_OF_BIRTH_REQUIRED: 'Date of birth is required',
  ACCESS_TOKEN_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_NOT_EXIST: 'Used refresh token or not exist',
  LOGOUT_SUCCESS: 'Logout success',
  EMAIL_VERIFY_TOKEN_REQUIRED: 'Email verify token is required',
  EMAIL_ALREADY_VERIFIED: 'Email already verified',
  EMAIL_VERIFY_SUCCESS: 'Email verify success',
  USER_NOT_FOUND: 'User not found',
  RESEND_EMAIL_VERIFY_SUCCESS: 'Resend email verify success',
  EMAIL_NOT_VERIFIED: 'Email not verified',
  CHECK_EMAIL_TO_VERIFY: 'Please check your email to verify',
  FORGOT_PASSWORD_TOKEN_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Verify forgot password success',
  INVALID_FORGOT_PASSWORD_TOKEN: 'Forgot password token is invalid',
  RESET_PASSWORD_SUCCESS: 'Reset password success'
}
